### ISSUE TITLE
report_alignment issue with non-numerized alignment

### ISSUE THREAD

**Issue by odoluca** [odoluca/Fast-NW-and-SW-Pairwise-alignment-using-numba-JIT#3]
using pairwise_standart.py

a="ATGTCA"
b="TGATCGTAGC"
input=localms_align(a,b,1,-1,-1,-1)
report_alignment( linput )
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:/Users/Osman/PycharmProjects/G4relation/pairwise_standard.py", line 706, in report_alignment
    print("".join([conversion_dict[x] for x in a]))
  File "C:/Users/Osman/PycharmProjects/G4relation/pairwise_standard.py", line 706, in <listcomp>
    print("".join([conversion_dict[x] for x in a]))
KeyError: 'A'

**Comment by odoluca** [comment]
the report_alignment() is fixed.
